-- Seeded reference data. Run by `supabase db reset` after migrations.
-- Connector catalog mirrors frontend src/data/connectors.tsx (50 entries).

insert into public.connectors (id, name, "group", icon_class, tint, operations) values
  ('gmail', 'Gmail', 'apps', 'text-rose-500', 'bg-rose-50 text-rose-500',
    '{"new_email":{"id":"new_email","label":"New email","filterableFields":["from","subject","label","has_attachment"],"configFields":["account","label"]},"send_email":{"id":"send_email","label":"Send email","configFields":["to","subject","body"]},"draft_email":{"id":"draft_email","label":"Draft email","configFields":["to","subject","body"]},"search_email":{"id":"search_email","label":"Search email","filterableFields":["from","subject","after"]}}'::jsonb),
  ('outlook', 'Outlook', 'apps', 'text-blue-600', 'bg-blue-50 text-blue-600',
    '{"new_email":{"id":"new_email","label":"New email","filterableFields":["from","subject","folder"]},"send_email":{"id":"send_email","label":"Send email","configFields":["to","subject","body"]}}'::jsonb),
  ('outlook_calendar', 'Outlook Calendar', 'apps', 'text-sky-600', 'bg-sky-50 text-sky-600',
    '{"event_started":{"id":"event_started","label":"Event started"},"event_ended":{"id":"event_ended","label":"Event ended"},"create_event":{"id":"create_event","label":"Create event"}}'::jsonb),
  ('onedrive', 'OneDrive', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"file_created":{"id":"file_created","label":"File created","filterableFields":["folder","name_contains"]},"file_modified":{"id":"file_modified","label":"File modified","filterableFields":["folder"]}}'::jsonb),
  ('sharepoint', 'SharePoint', 'apps', 'text-blue-700', 'bg-blue-50 text-blue-700',
    '{"file_created":{"id":"file_created","label":"File created","filterableFields":["site","library","name_contains"]},"file_modified":{"id":"file_modified","label":"File modified","filterableFields":["site"]}}'::jsonb),
  ('google_drive', 'Google Drive', 'apps', 'text-green-600', 'bg-green-50 text-green-600',
    '{"file_created":{"id":"file_created","label":"File created","filterableFields":["folder","type"]},"file_shared":{"id":"file_shared","label":"File shared with me"}}'::jsonb),
  ('dropbox', 'Dropbox', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"file_uploaded":{"id":"file_uploaded","label":"File uploaded","filterableFields":["folder"]}}'::jsonb),
  ('box', 'Box', 'apps', 'text-blue-600', 'bg-blue-50 text-blue-600',
    '{"file_uploaded":{"id":"file_uploaded","label":"File uploaded","filterableFields":["folder"]}}'::jsonb),
  ('slack', 'Slack', 'apps', 'text-violet-500', 'bg-violet-50 text-violet-500',
    '{"message_posted":{"id":"message_posted","label":"Message posted","filterableFields":["channel","user","contains"]},"slash_command":{"id":"slash_command","label":"Slash command","filterableFields":["command"]},"post_message":{"id":"post_message","label":"Post message","configFields":["channel","text"]},"dm_user":{"id":"dm_user","label":"DM user","configFields":["user","text"]}}'::jsonb),
  ('teams', 'Microsoft Teams', 'apps', 'text-violet-700', 'bg-violet-50 text-violet-700',
    '{"message_posted":{"id":"message_posted","label":"Message posted","filterableFields":["channel","user"]},"meeting_ended":{"id":"meeting_ended","label":"Meeting ended"}}'::jsonb),
  ('discord', 'Discord', 'apps', 'text-indigo-500', 'bg-indigo-50 text-indigo-500',
    '{"message_posted":{"id":"message_posted","label":"Message posted","filterableFields":["channel","contains"]}}'::jsonb),
  ('hubspot', 'HubSpot', 'apps', 'text-orange-500', 'bg-orange-50 text-orange-500',
    '{"create_contact":{"id":"create_contact","label":"Create contact","configFields":["email","name","company"]},"update_deal":{"id":"update_deal","label":"Update deal","configFields":["deal_id","stage"]}}'::jsonb),
  ('salesforce', 'Salesforce', 'apps', 'text-sky-500', 'bg-sky-50 text-sky-500',
    '{"create_lead":{"id":"create_lead","label":"Create lead","configFields":["email","company"]}}'::jsonb),
  ('pipedrive', 'Pipedrive', 'apps', 'text-emerald-600', 'bg-emerald-50 text-emerald-600',
    '{"deal_created":{"id":"deal_created","label":"Deal created","filterableFields":["pipeline","value_gt"]},"deal_won":{"id":"deal_won","label":"Deal won"}}'::jsonb),
  ('intercom', 'Intercom', 'apps', 'text-blue-600', 'bg-blue-50 text-blue-600',
    '{"conversation_started":{"id":"conversation_started","label":"Conversation started","filterableFields":["tag"]},"reply_received":{"id":"reply_received","label":"Reply received"}}'::jsonb),
  ('front', 'Front', 'apps', 'text-rose-600', 'bg-rose-50 text-rose-600',
    '{"conversation_assigned":{"id":"conversation_assigned","label":"Conversation assigned"},"reply_received":{"id":"reply_received","label":"Reply received","filterableFields":["inbox"]}}'::jsonb),
  ('notion', 'Notion', 'apps', 'text-neutral-900', 'bg-neutral-100 text-neutral-900',
    '{"add_row":{"id":"add_row","label":"Add database row","configFields":["database_id","properties"]},"update_page":{"id":"update_page","label":"Update page","configFields":["page_id"]}}'::jsonb),
  ('confluence', 'Confluence', 'apps', 'text-blue-600', 'bg-blue-50 text-blue-600',
    '{"page_published":{"id":"page_published","label":"Page published","filterableFields":["space"]},"page_updated":{"id":"page_updated","label":"Page updated"}}'::jsonb),
  ('stripe', 'Stripe', 'apps', 'text-indigo-500', 'bg-indigo-50 text-indigo-500',
    '{"invoice_paid":{"id":"invoice_paid","label":"Invoice paid","filterableFields":["amount","customer_email"]},"subscription_canceled":{"id":"subscription_canceled","label":"Subscription canceled","filterableFields":["plan_id"]}}'::jsonb),
  ('quickbooks', 'QuickBooks', 'apps', 'text-emerald-500', 'bg-emerald-50 text-emerald-500',
    '{"create_invoice":{"id":"create_invoice","label":"Create invoice","configFields":["customer","amount"]}}'::jsonb),
  ('shopify', 'Shopify', 'apps', 'text-emerald-600', 'bg-emerald-50 text-emerald-600',
    '{"order_created":{"id":"order_created","label":"Order created","filterableFields":["total_gt","tag"]},"customer_created":{"id":"customer_created","label":"Customer created"}}'::jsonb),
  ('zendesk', 'Zendesk', 'apps', 'text-lime-600', 'bg-lime-50 text-lime-600',
    '{"new_ticket":{"id":"new_ticket","label":"New ticket","filterableFields":["priority","tag","channel"]},"update_ticket":{"id":"update_ticket","label":"Update ticket","configFields":["ticket_id","status"]}}'::jsonb),
  ('google_calendar', 'Google Calendar', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"event_ended":{"id":"event_ended","label":"Event ended","filterableFields":["calendar","attendee_count_gt"]},"create_event":{"id":"create_event","label":"Create event","configFields":["title","when"]}}'::jsonb),
  ('calendly', 'Calendly', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"event_scheduled":{"id":"event_scheduled","label":"Event scheduled"},"event_canceled":{"id":"event_canceled","label":"Event canceled"}}'::jsonb),
  ('airtable', 'Airtable', 'apps', 'text-yellow-500', 'bg-yellow-50 text-yellow-500',
    '{"new_record":{"id":"new_record","label":"New record","filterableFields":["table","view"]}}'::jsonb),
  ('github', 'GitHub', 'apps', 'text-neutral-900', 'bg-neutral-100 text-neutral-900',
    '{"pr_opened":{"id":"pr_opened","label":"PR opened","filterableFields":["repo","author"]},"issue_opened":{"id":"issue_opened","label":"Issue opened","filterableFields":["repo","label"]}}'::jsonb),
  ('linear', 'Linear', 'apps', 'text-violet-600', 'bg-violet-50 text-violet-600',
    '{"issue_created":{"id":"issue_created","label":"Issue created","filterableFields":["team","label"]},"issue_updated":{"id":"issue_updated","label":"Issue updated","filterableFields":["team","status"]}}'::jsonb),
  ('jira', 'Jira', 'apps', 'text-blue-600', 'bg-blue-50 text-blue-600',
    '{"issue_created":{"id":"issue_created","label":"Issue created","filterableFields":["project","type"]},"issue_updated":{"id":"issue_updated","label":"Issue updated","filterableFields":["project","status"]}}'::jsonb),
  ('asana', 'Asana', 'apps', 'text-rose-500', 'bg-rose-50 text-rose-500',
    '{"task_created":{"id":"task_created","label":"Task created","filterableFields":["project"]},"task_completed":{"id":"task_completed","label":"Task completed"}}'::jsonb),
  ('trello', 'Trello', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"card_moved":{"id":"card_moved","label":"Card moved","filterableFields":["board","list"]}}'::jsonb),
  ('clickup', 'ClickUp', 'apps', 'text-violet-600', 'bg-violet-50 text-violet-600',
    '{"task_created":{"id":"task_created","label":"Task created","filterableFields":["space","list"]}}'::jsonb),
  ('twilio', 'Twilio', 'apps', 'text-red-600', 'bg-red-50 text-red-600',
    '{"sms_received":{"id":"sms_received","label":"SMS received","filterableFields":["from","contains"]},"send_sms":{"id":"send_sms","label":"Send SMS","configFields":["to","body"]}}'::jsonb),
  ('sendgrid', 'SendGrid', 'apps', 'text-blue-600', 'bg-blue-50 text-blue-600',
    '{"send_email":{"id":"send_email","label":"Send email","configFields":["to","template_id"]},"bounce_received":{"id":"bounce_received","label":"Bounce received"}}'::jsonb),
  ('mailchimp', 'Mailchimp', 'apps', 'text-yellow-500', 'bg-yellow-50 text-yellow-500',
    '{"subscriber_added":{"id":"subscriber_added","label":"Subscriber added","filterableFields":["list"]},"campaign_sent":{"id":"campaign_sent","label":"Campaign sent"}}'::jsonb),
  ('docusign', 'DocuSign', 'apps', 'text-yellow-600', 'bg-yellow-50 text-yellow-600',
    '{"envelope_signed":{"id":"envelope_signed","label":"Envelope signed"},"send_envelope":{"id":"send_envelope","label":"Send envelope","configFields":["to","template"]}}'::jsonb),
  ('tableau', 'Tableau', 'apps', 'text-blue-700', 'bg-blue-50 text-blue-700',
    '{"data_refresh":{"id":"data_refresh","label":"Data refresh","filterableFields":["workbook"]},"query_dataset":{"id":"query_dataset","label":"Query dataset","configFields":["dataset","query"]}}'::jsonb),
  ('snowflake', 'Snowflake', 'apps', 'text-sky-500', 'bg-sky-50 text-sky-500',
    '{"query":{"id":"query","label":"Run query","configFields":["sql"]},"table_updated":{"id":"table_updated","label":"Table updated","filterableFields":["schema","table"]}}'::jsonb),
  ('bigquery', 'BigQuery', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"query":{"id":"query","label":"Run query","configFields":["sql"]}}'::jsonb),
  ('postgres', 'Postgres', 'apps', 'text-sky-700', 'bg-sky-50 text-sky-700',
    '{"row_inserted":{"id":"row_inserted","label":"Row inserted","filterableFields":["table"]},"query":{"id":"query","label":"Run query","configFields":["sql"]}}'::jsonb),
  ('segment', 'Segment', 'apps', 'text-emerald-500', 'bg-emerald-50 text-emerald-500',
    '{"event_tracked":{"id":"event_tracked","label":"Event tracked","filterableFields":["event","user_id"]}}'::jsonb),
  ('mixpanel', 'Mixpanel', 'apps', 'text-violet-600', 'bg-violet-50 text-violet-600',
    '{"cohort_changed":{"id":"cohort_changed","label":"Cohort changed","filterableFields":["cohort_id"]}}'::jsonb),
  ('amplitude', 'Amplitude', 'apps', 'text-blue-500', 'bg-blue-50 text-blue-500',
    '{"event_tracked":{"id":"event_tracked","label":"Event tracked","filterableFields":["event"]}}'::jsonb),
  ('vercel', 'Vercel', 'apps', 'text-neutral-900', 'bg-neutral-100 text-neutral-900',
    '{"deployment_succeeded":{"id":"deployment_succeeded","label":"Deployment succeeded","filterableFields":["project"]},"deployment_failed":{"id":"deployment_failed","label":"Deployment failed"}}'::jsonb),
  ('netlify', 'Netlify', 'apps', 'text-cyan-600', 'bg-cyan-50 text-cyan-600',
    '{"deployment_succeeded":{"id":"deployment_succeeded","label":"Deployment succeeded"}}'::jsonb),
  ('s3', 'AWS S3', 'apps', 'text-orange-600', 'bg-orange-50 text-orange-600',
    '{"object_created":{"id":"object_created","label":"Object created","filterableFields":["bucket","prefix"]},"object_deleted":{"id":"object_deleted","label":"Object deleted"}}'::jsonb),
  ('pagerduty', 'PagerDuty', 'apps', 'text-emerald-600', 'bg-emerald-50 text-emerald-600',
    '{"incident_triggered":{"id":"incident_triggered","label":"Incident triggered","filterableFields":["service","urgency"]},"incident_resolved":{"id":"incident_resolved","label":"Incident resolved"}}'::jsonb),
  ('ai', 'AI', 'ai', 'text-fuchsia-500', 'bg-fuchsia-50 text-fuchsia-500',
    '{"classify":{"id":"classify","label":"Classify","configFields":["input","categories"]},"summarize":{"id":"summarize","label":"Summarize","configFields":["input","max_words"]},"draft":{"id":"draft","label":"Draft text","configFields":["prompt","tone"]},"extract":{"id":"extract","label":"Extract fields","configFields":["input","schema"]}}'::jsonb),
  ('schedule', 'Schedule', 'system', 'text-amber-500', 'bg-amber-50 text-amber-500',
    '{"on_schedule":{"id":"on_schedule","label":"On schedule","configFields":["mode","interval_minutes","cron"]}}'::jsonb),
  ('internal_email', 'Internal Email', 'system', 'text-emerald-600', 'bg-emerald-50 text-emerald-600',
    '{"email_received":{"id":"email_received","label":"Email received","filterableFields":["from","subject","has_attachment"]}}'::jsonb),
  ('webhook', 'Webhook', 'system', 'text-teal-600', 'bg-teal-50 text-teal-600',
    '{"request_received":{"id":"request_received","label":"Request received","filterableFields":["path","method"]}}'::jsonb),
  ('manual', 'Manual', 'system', 'text-neutral-700', 'bg-neutral-100 text-neutral-700',
    '{"run_now":{"id":"run_now","label":"Run now"}}'::jsonb)
on conflict (id) do update set
  name = excluded.name,
  "group" = excluded."group",
  icon_class = excluded.icon_class,
  tint = excluded.tint,
  operations = excluded.operations,
  updated_at = now();

-- Default KB tags.
insert into public.kb_tags (name, color) values
  ('research', 'sky'),
  ('design', 'violet'),
  ('finance', 'emerald'),
  ('legal', 'amber'),
  ('engineering', 'rose')
on conflict (name) do nothing;
